### ISSUE TITLE
I nead to automate some validation 

### ISSUE THREAD

**Issue by hdsoftware** [anskaffelser/vefa-validator#64]
Im sorry to bother you here, but I could not find any place else to ask for help.  If there is an other place, please let me know..

I have created a WEB service that our customers use to generate EHF files.  In some situations, I have to manually edit some of the files, not many, but some - and I have to use the online validator provided by you guys, which is a fine solution for us.  But still, its very manual and Im trying to automate this a little more. I know that you guys dont want us to automate using your site, so therfore I decided to build my own validator.  Please note - Im not a JAVA guy, so this is a complete unknown world to me. But to prepare my self for this task I have used a week with self study on JAVA so I pretty much understand the language and some of the solution construct.

My quest is, or should be simple...
I have downloaded the complete source for the validator
Then I tried to figure out the tool to use for compiling.  I ended up with Apache NetBeans, simpy because googeling POM.XML points directly to APACHE, which I found is behind NetBeans.

Trying to build things in NetBeans fails with lots of errors saying that Im missing stuff.
I then read all the "issues" at this git and found in one of them that you are using MAVEN for compiling.  I then read me up on Maven and found that I should do the compiling stuff in a terminal window.  
I then downloaded Apache Maven, unpacked it to a place on the drive an added it to the PATH. 
MVN --VERSION returns 
Maven version 3.8.4
Java version 17.0.1 from Oracle
etc.
I then opened CMD on my Windows and CD to project folder. Typed MVN VERIFY and it started - nice - but still fails...
Hers some of the result:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for VEFA Validator :: Parent 2.1.1-SNAPSHOT:
[INFO]
[INFO] VEFA Validator :: Parent ........................... SUCCESS [  0.003 s]
[INFO] VEFA Validator :: API .............................. FAILURE [  1.068 s]
[INFO] VEFA Validator :: Core ............................. SKIPPED
[INFO] VEFA Validator :: Tester ........................... SKIPPED
[INFO] VEFA Validator :: Build ............................ SKIPPED
[INFO] VEFA Validator :: Repo ............................. SKIPPED
[INFO] VEFA Validator :: Distribution ..................... SKIPPED
[INFO] VEFA Validator :: Web .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Im pretty sure the problem is me, but Im asking for a little help here to complete this simple task

The rest of the result is a huge exception message and it goes as follows:

Exception in thread "main" java.lang.Error: java.lang.reflect.InvocationTargetException
        at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
        at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.<init>(BGMBuilder.java:147)
        at com.sun.tools.xjc.reader.xmlschema.BGMBuilder.build(BGMBuilder.java:117)
        at com.sun.tools.xjc.ModelLoader.annotateXMLSchema(ModelLoader.java:425)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
        at com.sun.tools.xjc.Driver.run(Driver.java:333)
        at org.codehaus.mojo.jaxb2.AbstractXjcMojo.execute(AbstractXjcMojo.java:316)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
        ... 29 more
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
        at com.sun.tools.xjc.reader.Ring.get(Ring.java:113)
        at com.sun.tools.xjc.reader.xmlschema.BindingComponent.getClassSelector(BindingComponent.java:65)
        at com.sun.tools.xjc.reader.xmlschema.ColorBinder.<init>(ColorBinder.java:62)
        at com.sun.tools.xjc.reader.xmlschema.BindGreen.<init>(BindGreen.java:63)
        ... 35 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.sun.tools.xjc.reader.Ring.get(Ring.java:102)
        ... 38 more
Caused by: java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
        at java.base/java.lang.Class.getConstructor0(Class.java:3578)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
        at com.sun.tools.xjc.reader.Ring.get(Ring.java:100)
        at com.sun.tools.xjc.reader.xmlschema.DefaultClassBinder.<init>(DefaultClassBinder.java:98)
        at com.sun.tools.xjc.reader.xmlschema.ClassSelector.<init>(ClassSelector.java:214)
        ... 44 more
Caused by: java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 51 more

**Comment by klakegg** [comment]
Software development on your local machine is not subject to support from this project.
