### ISSUE TITLE
NullPointerException in latest Docker Image

### ISSUE THREAD

**Issue by phax** [anskaffelser/vefa-validator#66]
Please make sure these boxes are checked before submitting your issue - thank you!

- [X] Fixing my submitted issue is done by making changes to code in this repository.

Your issue here:

```
java.lang.NullPointerException
        at no.difi.vefa.validator.tester.Tester.validate(Tester.java:104)
```

With this rule file 
[BR-CO-17.xml.txt](https://github.com/anskaffelser/vefa-validator/files/8450480/BR-CO-17.xml.txt)

Edit:

https://github.com/anskaffelser/vefa-validator/blob/2.1.0/validator-tester/src/main/java/no/difi/vefa/validator/tester/Tester.java#L104

It is weird, because it seems to interpret the file as a TestSet *and* a Test???
```
[09:30:14][INFO ][Tester                 ]: Test '/src/cii/examples/XRechnung-O.xml'
[09:30:15][INFO ][Tester                 ]: TestSet '/src/test/cii/BR-CO-15-2.xml'
[09:30:15][INFO ][Tester                 ]: TestSet '/src/test/cii/BR-CO-17.xml'
[09:30:15][WARN ][Tester                 ]: Test '/src/test/cii/BR-CO-17.xml' (null)
java.lang.NullPointerException
        at no.difi.vefa.validator.tester.Tester.validate(Tester.java:104)
[09:30:15][INFO ][Tester                 ]: 15 tests performed, 0 tests failed
```

**Comment by klakegg** [comment]
Fixed in [f115fd5](https://github.com/anskaffelser/vefa-validator/commit/f115fd5ccfc13e9c008e13bdb2063ee832d6c91d).
 
This error presented is fixed by making the xml valid in ConnectingEurope/eInvoicing-EN16931#314.
