### ISSUE TITLE
EmptyFileException mulig bug i validator

### ISSUE THREAD

**Issue by adrianSoria** [anskaffelser/vefa-validator#67]
Please make sure these boxes are checked before submitting your issue - thank you!

- [x] Fixing my submitted issue is done by making releases in this repository.

Your issue here:
Hello we are using Vefa validator since 2015. We upgraded to 2.1.0 validator-core from January 2022.
We get warnings when using the validator with an inputstream:

```
public class Validator implements Closeable {
    public Validation validate(InputStream inputStream) {
        return validate(new ValidationSourceImpl(inputStream));
    }
....
}
```
StackTrace:
```
21936 [main] WARN  n.d.v.validator.ValidationInstance - Empty file 
java.io.IOException: Empty file
	at no.difi.vefa.validator.ValidationInstance.loadDocument(ValidationInstance.java:122) [validator-core-2.1.0.jar:na]
	at no.difi.vefa.validator.ValidationInstance.<init>(ValidationInstance.java:74) [validator-core-2.1.0.jar:na]
	at no.difi.vefa.validator.ValidationInstance.of(ValidationInstance.java:53) [validator-core-2.1.0.jar:na]
	at no.difi.vefa.validator.Validator.validate(Validator.java:87) [validator-core-2.1.0.jar:na]
	at no.difi.vefa.validator.Validator.validate(Validator.java:66) [validator-core-2.1.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
```

There seems to be an issue with you  loadDocument() method in the ValidationInstance. This occurs in production. 
We have 543 000 incidents in production.

```
    private void loadDocument(InputStream inputStream) throws ValidatorException, IOException {
       ....

        // Read first 10kB for detections
        byte[] bytes = new byte[10 * 1024];
        int length = byteArrayInputStream.read(bytes);

        if (length == -1)
            throw new IOException("Empty file");

```
Please contact us if you need more information.

**Comment by adrianSoria** [comment]
Looks like Jiteg removed the code that triggered the exception 13.feb 2022 in commit 71b6868d.

**Comment by adrianSoria** [comment]
Kan vi få hjelp til dette? @klakegg  Vi får fortsatt en del feil.

**Comment by klakegg** [comment]
I see you have confirmed this issue is fixed by making changes in the repository. What changes do you suggest?

**Comment by adrianSoria** [comment]
@klakegg the changes are not released.  I suggest you make a release with the fix.

**Comment by adrianSoria** [comment]
Har versjon 2.2.0 fikset dette? @klakegg
